---
# Source: openchoreo-data-plane/charts/openchoreo-data-plane/templates/cluster-agent/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-agent-dataplane
  namespace: openchoreo-data-plane
  labels:
    helm.sh/chart: openchoreo-data-plane-1.2.5
    app.kubernetes.io/name: openchoreo-data-plane
    app.kubernetes.io/instance: openchoreo-data-plane
    app.kubernetes.io/version: "v1.2.5"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: openchoreo
    app.kubernetes.io/component: cluster-agent