---
# Source: kgateway/charts/kgateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kgateway
  namespace: openchoreo-data-plane
  labels:
    helm.sh/chart: kgateway-v2.3.1
    kgateway: kgateway
    app.kubernetes.io/name: kgateway
    app.kubernetes.io/instance: kgateway
    app.kubernetes.io/version: "v2.3.1"
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: Helm