#!/usr/bin/env bash
# Regenerate repos/platform-charts/worker-birth-kit/crds/external-secrets.yaml from the pinned external-secrets
# dependency (run after bumping it; hack/tests/test_birth_kit.sh fails until you do).
# Why crds/: Helm maps every templated object to an API before it creates anything, so a ClusterSecretStore in
# templates/ fails the whole install ("no matches for kind") while its CRD is only another template. Helm installs
# crds/ first: one copy per ESO kind in templates/ (ClusterSecretStore, ExternalSecret, ClusterExternalSecret). The
# copies carry Helm ownership metadata for release worker-birth-kit/argocd, so the same install adopts
# them as the subchart's templated CRDs, which then own upgrades (Helm never upgrades crds/).
set -euo pipefail
cd "$(dirname "$0")/.."
kit=repos/platform-charts/worker-birth-kit
release=worker-birth-kit namespace=argocd   # = HelmChartProxy worker-birth-kit releaseName/namespace
version=$(yq '.dependencies[] | select(.name=="external-secrets") | .version' $kit/Chart.yaml)
helm dependency build $kit >/dev/null
{
  echo "# GENERATED by hack/birth-kit-crds.sh from external-secrets $version: do not edit."
  echo "# Bootstrap copies for the first install only (see the script); owned by release $release/$namespace."
  helm template $release $kit -n $namespace --set clusterName=crds \
    --show-only charts/external-secrets/templates/crds/clusterexternalsecret.yaml \
    --show-only charts/external-secrets/templates/crds/clustersecretstore.yaml \
    --show-only charts/external-secrets/templates/crds/externalsecret.yaml |
    yq ".metadata.labels[\"app.kubernetes.io/managed-by\"] = \"Helm\"
      | .metadata.annotations[\"meta.helm.sh/release-name\"] = \"$release\"
      | .metadata.annotations[\"meta.helm.sh/release-namespace\"] = \"$namespace\"
      | ... comments = \"\""
} > $kit/crds/external-secrets.yaml
echo "wrote $kit/crds/external-secrets.yaml (external-secrets $version)"
