apiVersion: v1
kind: Service
metadata:
  name: argocd-agent-principal-external
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: principal
    app.kubernetes.io/part-of: argocd-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: grpc
      port: 443
      targetPort: 8443
      nodePort: {{ .Values.hub.principalNodePort }}
