apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: podinfo
spec:
  requestedFreight:
    - origin: { kind: Warehouse, name: podinfo }
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - task: { name: bump-env-values }
          vars:
            - { name: env, value: dev }
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: podinfo
spec:
  requestedFreight:
    - origin: { kind: Warehouse, name: podinfo }
      sources:
        stages: [dev]
  promotionTemplate:
    spec:
      steps:
        - task: { name: bump-env-values }
          vars:
            - { name: env, value: test }
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: podinfo
spec:
  requestedFreight:
    - origin: { kind: Warehouse, name: podinfo }
      sources:
        stages: [test]
  promotionTemplate:
    spec:
      steps:
        - task: { name: bump-env-values }
          vars:
            - { name: env, value: prod }
