apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: podinfo
  namespace: podinfo
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/stefanprodan/podinfo
        imageSelectionStrategy: SemVer
        constraint: ^6.0.0
        discoveryLimit: 5
